name: 'Regenerate README'
description: 'Regenerate and commit README from template'
inputs:
  input-file-name:
    description: 'Template README file'
    required: true
    default: 'README.template.md'
  output-file-name:
    description: 'Output README file'
    required: true
    default: 'README.md'
  key:
    description: "key, in template file, to replace"
    required: True
  value:
    description: "value to substitute in template file"
    required: True
  git-email:
    description: "email for git configuration"
    required: True
    default: ${{ git.email }}
  git-name:
    description: "name for git configuration"
    required: True
    default: ${{ git.name }}
runs:
  using: 'node12'
  main: 'index.js'
