name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get Help Text
      id: get_help
      run: |
        echo ::set-output name=HELP_TEXT::$(node main.js -h)
    - name: Regenerate README.md
      uses: ./
      with:
        key: help
        value: ${{ steps.get_help.outputs.HELP_TEXT }}
