name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Regenerate README.md
      uses: ./
      with:
        key: help
        value: hello
