name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get Help Text
      run: |
        help_text=$(node main.js -h)
        help_text="${help_text//'%'/'%25'}"
        help_text="${help_text//$'\n'/'%0A'}"
        help_text="${help_text//$'\r'/'%0D'}"
        echo "::set-env name=HELP_TEXT::$help_text"
    - name: Print HELP_TEXT
      run: |
        echo "$HELP_TEXT"
    - name: Regenerate README.md
      uses: ./
      with:
        key: help
        value: ${{ env.HELP_TEXT }}
